name: Test

on:
  pull_request:
  
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  package: MediaViewer

jobs:
  test:
    runs-on: macos-latest
    
    env:
      IOS_SIMULATOR: "iPhone 14"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build
        run: xcodebuild build -scheme ${{ env.package }} -destination "name=${{ env.IOS_SIMULATOR }}"
        
      - name: Run tests
        run: xcodebuild test -scheme ${{ env.package }} -destination "name=${{ env.IOS_SIMULATOR }}"
